Controllers/RessourcesController.cs
using Microsoft.AspNetCore.Mvc;
using BookingPlatform.Data;
using BookingPlatform.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace BookingPlatform.Controllers
{
  
    public class RessourcesController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _env;

        public RessourcesController(AppDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _context.Resources.ToListAsync());
        }

        [HttpGet]
        public async Task<IActionResult> Index(string suche)
        {
            ViewData["Getressourcedetails"] = suche;
            var empquery = from x in _context.Resources select x;
            if (!string.IsNullOrEmpty(suche))
            {
                empquery = empquery.Where(x => x.Name.Contains(suche));
            }
            return View(await empquery.AsNoTracking().ToListAsync());
        }
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Resources == null)
            {
                return NotFound();
            }

            var ressource = await _context.Resources
                .FirstOrDefaultAsync(m => m.ResourceID == id);
            if (ressource == null)
            {
                return NotFound();
            }

            return View(ressource);
        }
        // GET: Ressources/Create
        public IActionResult Create(int Id)
        {
            if (Id == 0)
                return View(new Resources());
            else
                return View(_context.Resources.Find(Id));
        }

        // POST: Ressources/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Resources ressource)
        {
            ModelState.Remove("Buchungen");
            if (ModelState.IsValid)
            {
                if (ressource.ImageFile != null)
                {
                    var folder = "images/";
                    folder += Guid.NewGuid().ToString() + "_" + ressource.ImageFile.FileName;
                    ressource.ImageName = folder;
                    var serverFolder = Path.Combine(_env.WebRootPath, folder);

                    await ressource.ImageFile.CopyToAsync(new FileStream(serverFolder, FileMode.Create));
                }

                _context.Add(ressource);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(ressource);
        }

        // GET: Ressources/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Resources == null)
            {
                return NotFound();
            }

            var ressource = await _context.Resources.FindAsync(id);
            if (ressource == null)
            {
                return NotFound();
            }
            return View(ressource);
        }

        // POST: Ressources/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Resources ressource)
        {
            if (id != ressource.ResourceID)
            {
                return NotFound();
            }
            ModelState.Remove("Buchungen");
            if (ModelState.IsValid)
            {
                try
                {
                    if (ressource.ImageFile != null)
                    {
                        var folder = "images/";
                        folder += Guid.NewGuid().ToString() + "_" + ressource.ImageFile.FileName;
                        ressource.ImageName = folder;
                        var serverFolder = Path.Combine(_env.WebRootPath, folder);

                        await ressource.ImageFile.CopyToAsync(new FileStream(serverFolder, FileMode.Create));
                    }

                    _context.Update(ressource);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RessourceExists(ressource.ResourceID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(ressource);
        }

        // GET: Ressources/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Resources == null)
            {
                return NotFound();
            }

            var ressource = await _context.Resources
                .FirstOrDefaultAsync(m => m.ResourceID == id);
            if (ressource == null)
            {
                return NotFound();
            }

            return View(ressource);
        }

        // POST: Ressources/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Resources == null)
            {
                return Problem("Entity set 'RessourceDbContext.Ressources'  is null.");
            }
            var ressource = await _context.Resources.FindAsync(id);
            if (ressource != null)
            {
                _context.Resources.Remove(ressource);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RessourceExists(int id)
        {
            return _context.Resources.Any(e => e.ResourceID == id);
        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookingPlatform</title>
    <link rel="stylesheet" href="~/css/bootswaschTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookingPlatform.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/BookingPlatform.styles.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-white border-bottom box-shadow mb-3 mt-1">
  <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/css/logo/Logo.png" asp-append-version="true" width="220px" Height="60px" /></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor03">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home
            <span class="visually-hidden">(current)</span>
          </a>
        </li>
      
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Ressources" asp-action="Index">Ressourcen</a>
         </li>
            <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="BookingManagement" asp-action="Index">Buchungen</a>
            </li>
            <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Administrators</a>
            </li>
            

                        <li class="nav-item">
                            
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="MeineBuchung">Meine Buchungen</a>
                        </li>

                       

                    
                     @*   <li class="nav-item">
                            <p>@User.Identity.Name</p>
                        </li>*@
      </ul>
    </div>
  </div>
</nav>
        @*Old Navbar
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 ">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/css/logo/Logo.png" asp-append-version="true" width="180px" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">

                            <a class="nav-link text-dark" asp-area="" asp-controller="Ressources" asp-action="Index">Ressource</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>*@
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
@*
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - BookingPlatform - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>